# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  
sphinx:
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - method: pip
      path: .
    
conda:
  environment: docs/requirements.yaml
